# Generated by Django 4.2.7 on 2025-04-20 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poker_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('FOLD', 'Fold'), ('CHECK', 'Check'), ('CALL', 'Call'), ('BET', 'Bet'), ('RAISE', 'Raise')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Card',
        ),
        migrations.AddField(
            model_name='game',
            name='community_cards',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='current_bet',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='game',
            name='dealer_position',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='phase',
            field=models.CharField(blank=True, choices=[('PREFLOP', 'Pre-flop'), ('FLOP', 'Flop'), ('TURN', 'Turn'), ('RIVER', 'River'), ('SHOWDOWN', 'Showdown')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='playergame',
            name='cards',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='playergame',
            name='current_bet',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='playergame',
            name='total_bet',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='gameaction',
            name='player_game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poker_api.playergame'),
        ),
    ]
