# Generated by Django 4.2.7 on 2025-06-22 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poker_api', '0002_gameaction_delete_card_game_community_cards_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='winner_info',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
