# Generated by Django 4.2.7 on 2025-06-22 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poker_api', '0003_game_winner_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameaction',
            name='phase',
            field=models.CharField(choices=[('PREFLOP', 'Pre-flop'), ('FLOP', 'Flop'), ('TURN', 'Turn'), ('RIVER', 'River')], default='PREFLOP', max_length=20),
        ),
    ]
