# Generated by Django 4.2.7 on 2025-06-23 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poker_api', '0004_gameaction_phase'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='hand_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='HandHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hand_number', models.PositiveIntegerField()),
                ('winner_info', models.TextField()),
                ('pot_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('community_cards', models.CharField(blank=True, max_length=100, null=True)),
                ('final_phase', models.CharField(choices=[('PREFLOP', 'Pre-flop'), ('FLOP', 'Flop'), ('TURN', 'Turn'), ('RIVER', 'River'), ('SHOWDOWN', 'Showdown')], max_length=20)),
                ('player_cards', models.TextField()),
                ('actions', models.TextField()),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hand_history', to='poker_api.game')),
            ],
            options={
                'ordering': ['-completed_at'],
                'unique_together': {('game', 'hand_number')},
            },
        ),
    ]
