# Generated by Django 4.2.7 on 2025-06-24 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poker_api', '0006_alter_game_winner_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='playergame',
            name='ready_for_next_hand',
            field=models.BooleanField(default=False),
        ),
    ]
