# Generated by Django 4.2.7 on 2025-06-24 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poker_api', '0007_playergame_ready_for_next_hand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='phase',
            field=models.CharField(blank=True, choices=[('PREFLOP', 'Pre-flop'), ('FLOP', 'Flop'), ('TURN', 'Turn'), ('RIVER', 'River'), ('SHOWDOWN', 'Showdown'), ('WAITING_FOR_PLAYERS', 'Waiting for players to be ready')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='handhistory',
            name='final_phase',
            field=models.CharField(choices=[('PREFLOP', 'Pre-flop'), ('FLOP', 'Flop'), ('TURN', 'Turn'), ('RIVER', 'River'), ('SHOWDOWN', 'Showdown'), ('WAITING_FOR_PLAYERS', 'Waiting for players to be ready')], max_length=20),
        ),
    ]
