# Generated by Django 4.2.7 on 2025-06-24 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poker_api', '0008_alter_game_phase_alter_handhistory_final_phase'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='playergame',
            unique_together={('game', 'seat_position'), ('game', 'player')},
        ),
    ]
