# Generated by Django 4.2.7 on 2025-06-26 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poker_api', '0009_alter_playergame_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='playergame',
            name='cashed_out',
            field=models.BooleanField(default=False),
        ),
    ]
