# Generated by Django 4.2.7 on 2025-06-26 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poker_api', '0010_playergame_cashed_out'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='game_summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playergame',
            name='final_stack',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='playergame',
            name='starting_stack',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
