# Generated by Django 4.2.7 on 2025-06-27 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poker_api', '0012_gamesummary'),
    ]

    operations = [
        migrations.AddField(
            model_name='playergame',
            name='left_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playergame',
            name='left_table',
            field=models.BooleanField(default=False),
        ),
    ]
